---
- name: Configure Maven slave node
  hosts: jenkins-slave
  become: true
  tasks:
    - name: Install java 21 corretto
      yum:
        name: java-21-amazon-corretto
        state: present

    - name: Download Maven
      get_url:
        url:  https://dlcdn.apache.org/maven/maven-3/3.9.14/binaries/apache-maven-3.9.14-bin.tar.gz
        dest: /opt

    - name: Extract the tar file
      unarchive:
        src: /opt/apache-maven-3.9.14-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: install git
      yum:
        name: git
      tags: install_git

    - name: check git version
      shell: git --version
      regsiter: git_version
      tags: install_git

    - name: print git version
      deub:
        var: {{ git_version.stdout }}
      tags: install_git  
             
