---
- name: Configure Maven slave node
  hosts: jenkins-slave
  become: true

  vars:
    kubectl_version: "v1.33.2"


  tasks:
    - name: Install java 21 corretto
      yum:
        name: java-21-amazon-corretto
        state: present

    - name: Download Maven
      get_url:
        url:  https://dlcdn.apache.org/maven/maven-3/3.9.14/binaries/apache-maven-3.9.14-bin.tar.gz
        dest: /opt

    - name: Extract the tar file
      unarchive:
        src: /opt/apache-maven-3.9.14-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: install git
      yum:
        name: git
        state: present
      tags: install_git

    - name: check git version
      shell: git --version
      register: git_version
      tags: install_git

    - name: print git version
      debug:
        var: git_version.stdout
      tags: install_git

    - name: Install docker
      yum:
        name: docker
        state: present
      tags: install_docker

    - name: enable & start docker
      service:
        name: docker
        enabled: yes
        state: started
      tags: install_docker

    - name: docker status
      command: service docker status
      register: docker_status
      tags: install_docker

    - name: print docker status
      debug:
        msg: "Docker service is {{ docker_status.stdout }}"
      tags: install_docker  

    - name: permission to docker sock
      file:
        path: /var/run/docker.sock
        state: file
        mode: 0777
      tags: install_docker  
             
    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      tags: install_kubectl  

    - name: Set kubectl path
      lineinfile:
        path: /etc/profile.d/kubectl.sh
        line: 'export PATH=$PATH:/usr/local/bin'
        create: yes
        mode: '0644'
      tags: install_kubectl    

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version_output
      changed_when: false
      tags: install_kubectl   

    - name: Display kubectl version
      debug:
        var: kubectl_version_output.stdout
      tags: install_kubectl 